function [parm, flow] =  build_structs()

    parm = struct('flowtype', [], ...
                  'rho', [], 'nu', [], 'grav', [], ...
                  'm', [], 'n', [], 'npoints', [], ...
                  'dx',[], 'dy', [], 'dt', [], ...
                  'ntst', [], ...
                  'xl', [], 'yl', [], ...
                  'ip', [], 'jp', [], 'im', [], 'jm', [], ... 
                  'atbounds', [], ...
                  'debugp', [] ...
                  );
          
    flow = struct('u', [], 'v', [], 'p', [], ...
                  'rhsu', [], 'rhsv', [], ...
                  'secrhsu', [], 'secrhsv', [], ...
                  'matrix_T', [], 'matrix_invT', [], ...
                  'div', [], 'dp', [] ...
                  );
              
end